name: update-repo

on: workflow_dispatch

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python packages
        run: pip install PyGithub packaging
      - name: Update repository
        run: |
          cd athena
          ./updateRepo.py
          ./rebuildRepo.py
