name: update-repo

on: workflow_dispatch

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version name
        id: version_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python packages
        run: pip install PyGithub
      - name: Update repository
        run: |
          cd athena
          ./updateRepo.py
          ./rebuildRepo.py
